### PR TITLE
Fix npm command

### PR DESCRIPTION
**Pull request by nucliweb**
- Fix npm command for install `http-server`

### CODE REVIEW

**Comment by belen-albeza** [comment]
Thanks for the typo :)

**Comment by nucliweb** [comment]
Hi @belen-albeza,

In the case of `http-server` with npm, what you think of include a `package.json` in the project for install this dependency in local scope?

**Comment by belen-albeza** [comment]
No, the use of `http-server` is a suggestion only. There are multiple ways of running a local server and including a `package.json` might be confusing for people who are not familiar with Node or npm.

**Comment by nucliweb** [comment]
👍

**Pull request merged**
